### ISSUE TITLE
Double scroll bars

### ISSUE THREAD

**Issue by luisfelipesdn12** [filippo-fonseca/portfolio#1]
# What happen? 

The website has two scroll bars, which can be prejudicial to the user experience, overall in mobile devices.

## Demonstration video:

https://user-images.githubusercontent.com/60361387/103039974-f8467780-4550-11eb-8723-944f5ea912df.mp4

**Comment by filippo-fonseca** [comment]
Hey!

Thanks for bringing this up. I was actually in the middle of fixing it :).

**Comment by filippo-fonseca** [comment]
Thank you for your video as well! I appreciate the effort.

**Comment by luisfelipesdn12** [comment]
> Hey!
> 
> Thanks for bringing this up. I was actually in the middle of fixing it :).

Oh, awesome! Sorry to interrupting :)

**Comment by filippo-fonseca** [comment]
Thank you for your video as well! I appreciate the effort.

**Comment by filippo-fonseca** [comment]
UPDATE: In progress now...
